### ISSUE TITLE
Refactor components with hooks

### ISSUE THREAD

**Issue by lenkon** [lenkon/math-magician#4]
Project name: Math Magicians - refactor with hooks❗️❗️

Project description: In this project the Calculator component that was developed in the past projects will be refactored. Instead of using class based components, now hooks will be used.

#### Project requirements:
- Refactor the Calculator component (`components/Calculator.js`) from a class based component to a functional component with *hooks*.
- After the refactor is done, test the app in the browser. It should keep the same functionality.

 ❗❗️❗️❗️❗️❗️ **IMPORTANT NOTE: If you already use functional components, you can create a GitHub issue in which you describe how you use functional components and ask for a code review based on your issue.**

#### Note: The project was at first developed using class based component. But it was refactored to a functional component based on code reviewer's feedback.

Project requirements link: https://github.com/microverseinc/curriculum-react-redux/blob/main/math-magicians/project_refactor_with_hooks.md

**Comment by roshan-bajgain** [comment]
Hi @lenkon, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- The calculator is working fine ✔️ 
- Refactor is done ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by lenkon** [comment]
Hi @roshan-bajgain , 

Thanks for your valuable time in going through my code.

Best Regards,
K. Inoulen Shanongba
